<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJfjYdx1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJfjYdx1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJfjYdx1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJfjYdx1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJfjYdx1\App_KernelDevDebugContainer([
    'container.build_hash' => 'JfjYdx1',
    'container.build_id' => '416c913d',
    'container.build_time' => 1692915743,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJfjYdx1');
